### ISSUE TITLE
java project

### ISSUE THREAD

**Issue by RomanS2N** [trade-manager/trade-manager#21]
Hello!

Tell me How will open trade-manager as a project in NetBeans?

**Comment by trade-manager** [comment]
Sorry I've never used netbeans

On Wed, May 4, 2016 at 8:05 AM, RomanS2N <notifications@github.com> wrote:

> Hello!
>
> Tell me How will open trade-manager as a project in NetBeans?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/trade-manager/trade-manager/issues/21>
>



-- 
TTFN
Simon
